version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: job_hunter_db
    environment:
      POSTGRES_DB: job_hunter
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  job-hunter-app:
    build: .
    container_name: job_hunter_app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/job_hunter
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER:-postgres}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD:-password}
    env_file:
      - .env
    depends_on:
      - db
    restart: always

volumes:
  postgres_data:
