version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: job_finder_db
    environment:
      POSTGRES_DB: job_hunter
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - job-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  job-finder-app:
    image: ghcr.io/viniciustck/project-job-finder-system:latest
    container_name: job_finder_app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/job_hunter
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
      JSEARCH_API_KEY: ${JSEARCH_API_KEY}
      ADZUNA_APP_ID: ${ADZUNA_APP_ID}
      ADZUNA_APP_KEY: ${ADZUNA_APP_KEY}
      GOOGLE_SEARCH_KEY: ${GOOGLE_SEARCH_KEY:-}
      GOOGLE_SEARCH_CX: ${GOOGLE_SEARCH_CX:-}
    ports:
      - "8080:8080"
    networks:
      - job-network
    restart: unless-stopped

networks:
  job-network:


volumes:
  postgres_data:
